### ISSUE TITLE
Problem: version number in Dashboard incorrect

### ISSUE THREAD

**Issue by joel-simpson** [JiscRDSS/rdss-archivematica#112]
When using rdss-archivematica, there is no way to know which version is being used. The Archivematica version is mentioned, but not the Jisc version of it (i.e. rdss-archivematica release number). 

The version page (e.g. https://archivematica.jisc-qa.archivematica.org/administration/version/) shows a version and an Agent Code. Both of these should reflect the rdss-archivematica release number. 
That way, a Dashboard user could confirm the version used in the UI. And, because the Agent Code is used in the Premis events, any AIP produced would also show the version used. 

Worth noting that there are some related issues - see: https://github.com/artefactual/archivematica/issues/658

**Comment by jhsimpson** [comment]
This is related to https://github.com/artefactual/archivematica/issues/658

**Comment by helenst** [comment]
The version number is set up in two places:

1. `archivematicaCommon/lib/version.py` which configures like so:
```
ARCHIVEMATICA_VERSION = (1, 6, 0)
```

This is what sets the version number on the dashboard page.

2. Migrations which update the `Agent` entry in the database:
```python
Agent.objects.filter(identifiertype='preservation system', name='Archivematica').update(identifiervalue='Archivematica-1.6.0')
```
This is the entry that displays as the Agent code on the dashboard page, and is also embedded in the METS file.

In addition to this, `setup_pipeline` picks up the version number from `ARCHIVEMATICA_VERSION` when AM is set up for the first time and changes the Agent database entry to match.

We could have `ARCHIVEMATICA_VERSION` take its value from an environment variable, this will mean that a custom version number could be set during deployment and would always show correctly on the dashboard. However, the value of the agent code would only be correct for a newly installed pipeline. When AM is upgraded and new data migrations are run, those values will be used instead, and `setup_pipeline` will not be able to override them again.

One possible answer to this is keeping a Jisc-specific data migration for the agent code on the Jisc fork. However, this would be a maintenance headache and we'd need to make sure it always runs after any core migration that sets a new value.

I propose creating a new management command for updating the version, this would take the value from `ARCHIVEMATICA_VERSION` and correctly set the agent code in the database, in the same way that `setup_pipeline` does now during installation, the difference being that this command could be run during deployment (after database migrations) so the version is always Jisc-specific (as configured) and always up to date, overwriting any migrated values.

How would we want the RDSS-specific values to look? Something like this?
```
Version: rdss-0.2.0
Agent code: Archivematica-rdss-0.2.0
```

**Comment by joel-simpson** [comment]
Good questions!
I don't have strong opinions on this, but I would say that version and agent code go together really, so there is no need for version to be anything other than the number. I feel like there should be advantages to having that exactly the same as the release tag (e.g. 0.2.0)
For the Agent Code - because we name the github repo rdss-archivematica, I'd be inclined to follow that pattern (not that it is any better than what you suggested, but I just have this intuition that the extra consistency could be helpful).  In other words, use 
```
Version: 0.2.0
Agent code: rdss-Archivematica-0.2
```
I've left off the final patch number because it isn't used in standard Archivematica (so am assuming that is by design but I will check on that!)

I will leave @sevein or @jhsimpson to comment on the implementation approaches. 

But I will clarify what I'd expect to see in our METS files. the snippet below is from a METS file produced in jisc-qa. 
```
<premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue>Archivematica-1.6</premis:linkingAgentIdentifierValue></premis:linkingAgentIdentifier>
```
Whatever we agree on as the right Agent code is what should appear as the `linkingAgentIdentifierValue`

**Comment by jhsimpson** [comment]
`Version: rdss-archivematica-0.2.0
Agent code: rdss-archivematica-0.2.0`

That would be my suggestion (i.e. identical string for both)

**Comment by sevein** [comment]
I'm late to this convo, sorry. @helenst I've seen #48 and it looks good to me. I imagine this is going to require an additional pull request against `rdss-archivematica` and some docs so we let the core team know about the new requirements? i.e. new mandatory environment variables and extra deployment steps during upgrades?

On a side note, I'm wondering if we should at some point approach this in a way where the version number becomes an inherent attribute of the Docker images to make sure that we don't mistakenly identify our artifacts because of external factors?
The solution envisioned in #48 makes possible to spread the version number across multiple components via environment attributes and deployment conventions which is a big step forward. My question is whether it's worth the effort to go a bit further and inject the version number during the build process, e.g.: I want to download `archivematica-dashboard:v1.2.3` (Docker image) and have the application be able to report us that it belongs to `rdss-archivematica vX.Y.Z` instead of having me to tell it.

When we build our Docker images from rdss-archivematica we can run `git describe --tags --always --dirty` to obtain a unique identifier. E.g. I'm on a topic branch doing some work and running that command gave me the following string: `v0.2.0-8-gf2873e4`. Now when I build the Dashboard image I could pass this string using build arguments, e.g.:

    $ docker build --build-arg RDSS_ARCHIVEMATICA_VERSION=v0.2.0-8-gf2873e4

The `Dockerfile` can make use of this variable to populate a file inside the image that could be read by the application, or we could patch the source code so the property becomes part of the code base.

There is another inconvenient. The version number of the preservation system is ultimately stored in the user's database. I suspect that this doesn't really help and it should be avoided. If we generate an `Event` that needs to keep record of the preservation system version number it could be persisted in a text field but I'm not sure what's the real value of maintaining a tuple in the `Agent` table for this purpose.

**Comment by helenst** [comment]
@sevein Yes, I am working on an rdss-archivematica pull request for that. I like your idea of building it into the docker image though.

I guess having it in the `Agent` table makes it easier to write out in the METS files in the same way as the other records although if we wanted to remove it I'm guessing some level abstraction could be used to still make the code work nicely (bear in mind I'm not hugely familiar with the workings of the METS generators...)
