### ISSUE TITLE
Problem: 'view raw' link for AIP broken on Archival Storage Tab of Dashboard 

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#43]
I did a search of AIPs in the Archival Storage tab.  I then tried the 'view raw' link under matching AIPs and got the error shown below.
![screen shot 2017-06-23 at 09 11 10 2](https://user-images.githubusercontent.com/25819534/27472651-0cd574d8-57f4-11e7-8286-271b3dd90d20.png)
![screen shot 2017-06-23 at 08 51 16 2](https://user-images.githubusercontent.com/25819534/27472689-38c49880-57f4-11e7-9695-77d8a2f0c2d3.png)

**Comment by mjaddis** [comment]
seems to work fine in the Jisc deployments - no error seen in 480-dev.

**Comment by sevein** [comment]
It seems that Elasticsearch was down. I'm going to close this because I don't think this is something that we can fix - feel free to reopen if needed. You're seeing a traceback because Django is being deployed in debug mode. When the debug mode is disabled though the error message is simpler and tells the user that the Elasticsearch server is unaccessible.

This is the middleware that catches the Elasticsearch client exception: https://github.com/artefactual/archivematica/blob/stable/1.6.x/src/dashboard/src/middleware/common.py#L48-L67.
