### ISSUE TITLE
Problem: No transfer approval dialog for big datasets 

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#56]
When trying to do a Transfer for the 10.1055 dataset (117 objects) in the QA env (interactive workflow transfer source), no dialog box comes up to approve/reject the transfer and hence it's not possible to initiate processing of the dataset.  The same problem occurs in the Jisc 480 dev env (10.1029, 10.1006, 10.1055) so this is not specific to the QA env.   

In all cases, the SS seems to do it's job and get the dataset into /var/archivematica/sharedDirectory/tmp/.  For example, the last reported rsync looks like this: ['rsync', '-t', '-O', '--protect-args', '-vv', '--chmod=ugo+rw', '-r', '/var/archivematica/storage_service/var/archivematica/sharedDirectory/tmp/tmpg0T28l/mja10/./', '/var/archivematica/sharedDirectory/tmp/tmpg0T28l/mja10/.'] and the files are in the target directory as they should be.

At this point what is meant to happen is that a dialog pops up in the Dashboard asking the user to approve the transfer.  On approval, the dataset should be moved to /var/archivematica/sharedDirectory/watchedDirectories/activeTransfers/standardTransfer/ and then /var/archivematica/sharedDirectory/currentlyProcessing.   But no dialog appears.   

If I do the same for a working dataset, then I see the exact same log entries for the SS and the Dashboard, but I also get the Approve Transfer dialog and entries appear in the mcp-server log that show the processing chain has started.   For the datasets that fail to get this far, all logs are silent and there are no entries in mcp-server.   I don't know why this should be the case.

**Comment by mamedin** [comment]
As workaround, in the QA env I have changed:

`def  _storage_api_session(timeout=5):` to `def _storage_api_session(timeout=300):`  at 
archivematica/src/archivematicaCommon/lib/storageService.py

It seems that this solves the issue.

I do not know if this value is huge or insufficient for the Jisc env. Can a developer take a look and select an adequate timeout setting or make other more appropriate changes?

**Comment by lower29** [comment]
I'm not sure that editing the timeout there is the correct thing to do - it seems a bit brute-force. I'd rather we try to find a better place to make this change.

I think it's [copy_files()](https://github.com/JiscRDSS/archivematica/blob/c4f0e75bd7582894a181e14ba9ae22707964969c/src/archivematicaCommon/lib/storageService.py#L185) that needs changing. Here's the current code:
```    url = _storage_service_url() + 'location/' + destination_location['uuid'] + '/'
    try:
        response = _storage_api_session().post(url, json=move_files)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        LOGGER.warning("Unable to move files with %s because %s", move_files, e.content)
        return (None, e)
    ret = response.json()
```

That call to `_storage_api_session()` isn't specifying a `timeout` value, so the default is being used. We could add `timeout=300` in this call instead, and then it would only affect the `move_files` operation, not all usage of the storage service API.

... But maybe some other usages of the API *should* be specifying a longer timeout to deal with large datasets? I don't know the Archivematica code well enough to be able to say what the impact is.

Also, it would make more sense to me to make the "copy files timeout" configurable via settings, rather than having to modify the code in order to change it.

Lastly, @mjaddis has reported that this problem with transfer of large datasets didn't occur in v1.6.0, so it may be a regression in v1.6.1. A code analysis may reveal what, if anything, has caused this change in behaviour.

@sevein Can you shed any further light on this?

**Comment by jhsimpson** [comment]
@lower29 I believe the issue was introduced in the qa/1.x branch with this PR https://github.com/artefactual/archivematica/pull/531

That PR was not included in the 1.6.0 or 1.6.1 public releases of Archivematica, but it is in the JiscRDSS/archivematica fork.

**Comment by lower29** [comment]
Thanks @jhsimpson, that makes sense and explains why this problem hasn't been seen in 1.6 or 1.6.1. Are you able to recommend what the fix should be? Should it be the workaround that @mamedin suggested or something more precise?

**Comment by mamedin** [comment]
The change proposed by Richard in the previous note, which consists of only changing the timeout value in the _storage_api_session () call, instead of changing the timeout value globally in the SS has been applied in the QA environment. Has been active in Jisc's QA environment for 10 days.

**Comment by mjaddis** [comment]
Yes, and confirmed as working in the QA env.  But the fix needs to be applied in JiscRDSS/archivematica otherwise it won't be included in deployments by Jisc, e.g. 480-dev?

**Comment by mjaddis** [comment]
https://jiscdev.atlassian.net/browse/RDSSARK-221

**Comment by lower29** [comment]
Can this issue be closed now?

**Comment by lower29** [comment]
Closing as https://github.com/JiscRDSS/archivematica/pull/30 has now been merged which will fix this.
