### ISSUE TITLE
Problem: processing of datasets containing no files stalls at the end of the Transfer stage

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#76]
If a Transfer in the Dashboard has no files, i.e. empty directories, then the Transfer stalls at the "Check transfer directory for objects" stage.  It doesn't fail but neither does it continue to the Ingest stage - it just sits there.    This is a particular problem if the Transfer has been initiated by the automation tools because the tools think the job is still running and doesn't move on to any other automated transfers.  

The Transfer process should either:

a) Fail very early in the process with a clear indication that there are no files to process, or
b) Complete the process with no files in the AIP/DIP, e.g. create a 'metadata only' AIP.

**Comment by mjaddis** [comment]
Related to: https://github.com/JiscRDSS/rdss-archivematica/issues/59

**Comment by joel-simpson** [comment]
I'd add this is also related to https://github.com/JiscRDSS/rdss-archivematica-automation-tools/issues/5
Fixes for that and for #59 should reduce the likelihood that this problem will occur. 
But it is possible that this will occur due to user error - i.e. a user creates a directory with no files in it and copies it into the Automated workflow directory.  
I recommend the best solution this issue is a) as Matthew described above. I can't see any situation where a user gets value from an AIP that had 0 files in it. So it should be called out as an error (e.g. so you see the "failed transfer" microservice reported in the dashboard) so that it is really obvious that something went wrong.

**Comment by mjaddis** [comment]
@joel-simpson @jhsimpson One thing to perhaps distinguish between is what happens for a dataset with no files in it at all v.s. a dataset that has something in the metadata directory, e.g. a metadata.csv file, but nothing in the objects directory.  For example, would someone perhaps want to create a 'metadata only' AIP, e.g. because files exist elsewhere or maybe because they've got files in a another AIP and they want to add some metadata in a 'metadata only AIP' and link that to an 'objects only AIP' by using an AIC?   Currently, if you put a metadata.csv file into the metadata directory of a transfer but put nothing in the objects folder then the transfer will stall at 'check transfer directory for objects' stage.  But the transfer as a whole can't be said to be 'empty'.  I don't know what the expected/desired behaviour is for 'metadata only' AIPs so this is just me flagging up that there may be more to think about than going straight for option (a) above.

**Comment by mjaddis** [comment]
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-266

**Comment by joel-simpson** [comment]
a good point @mjaddis. I could see this being useful as part of an iterative workflow, where running the dataset with metadata only would give you some metrics on the metadata. That might be pretty far out from where we are now, but option a) above closes the door on that approach. Option b) would clearly be safer. 
It also occurs to me that there is another project going on with a client looking to introduce the ability to create UUIDs for directories, so that metadata about them is retained even if they are empty. In other words, if a transfer includes directories or sub-directories that are empty of actual objects, they want the ability to reconstruct that later in a DIP. I may not have all the details exactly right, but point it out because I think it also supports taking approach b).  
Essentially Archivematica will process whatever you give it, report on it, and let users decide what has value and what doesn't, rather than assuming something with no objects is an error.
